scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairWest, function (sprite, location) {
    game.over(true)
})
game.showLongText("Trouvez tous les légumes avant la fin du temps imparti", DialogLayout.Full)
let mySprite = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ......ff............
    ......ff....ff......
    ......ff....ff......
    .....f.f...f.f......
    .....f.fffff.f......
    .....f.......ff.....
    ..f..f........ff....
    ...fff..f.f...ff....
    ....f........ff.....
    ..fff.........fff...
    ...f.........ff.....
    ...fff......fff.....
    ..f..ffffffff..ff...
    .f....11.11..f......
    ......11.11...f.....
    `, SpriteKind.Player)
info.setScore(0)
info.setLife(3)
controller.moveSprite(mySprite, 100, 100)
tiles.setTilemap(tilemap`niveau2`)
scene.cameraFollowSprite(mySprite)
tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairLadder)
info.startCountdown(100)
