scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairWest, function (sprite, location) {
    game.over(true)
})
game.showLongText("Trouvez tous les légumes avant la fin du temps imparti", DialogLayout.Full)
let mySprite = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ......ff............
    ......ff....ff......
    ......ff....ff......
    .....f.f...f.f......
    .....f.fffff.f......
    .....f.......ff.....
    ..f..f........ff....
    ..ffff..f.f...ff....
    ....ff.......ff.....
    .fffff......f.ffffff
    ...f..f.....fff.....
    ...fff..f..fffff....
    ..ff.ffffffff..ff...
    ......ff.ff..ff..f..
    ......ff.ff...ff....
    `, SpriteKind.Player)
info.setScore(0)
info.setLife(3)
controller.moveSprite(mySprite, 100, 100)
tiles.setTilemap(tilemap`niveau2`)
scene.cameraFollowSprite(mySprite)
tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairLadder)
info.startCountdown(100)
