def on_overlap_tile(sprite, location):
    game.over(True)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.stair_west,
    on_overlap_tile)

game.show_long_text("Vous êtes Rémi, rat parisien qui vient au secours des démunis",
    DialogLayout.CENTER)
game.show_long_text("Trouvez tous les légumes avant la fin du temps imparti, puis parvenez à sortir des égouts !",
    DialogLayout.CENTER)
mySprite = sprites.create(img("""
        ....................
            ....................
            ....................
            ....................
            ....................
            ......ff............
            ......ff....ff......
            ......ff....ff......
            .....fdf...fdf......
            .....fdfffffdf......
            .....fdddddddff.....
            ..f..fddddddddff....
            ...fffddfdfdddff....
            ....fddddddddff.....
            ..fffdddddddddfff...
            ...fdddddddddff.....
            ...fffddddddfff.....
            ..f..ffffffff..ff...
            .f.....1..1..f......
            ..............f.....
    """),
    SpriteKind.player)
info.set_score(0)
info.set_life(3)
controller.move_sprite(mySprite, 100, 100)
tiles.set_tilemap(tilemap("""
    niveau2
"""))
scene.camera_follow_sprite(mySprite)
tiles.place_on_random_tile(mySprite, sprites.dungeon.stair_ladder)
info.start_countdown(100)